# Generated by Django 3.0.2 on 2020-01-30 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Einweisable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('member_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('einweisable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='einweisungen.Einweisable')),
                ('activateable', models.BooleanField()),
            ],
            bases=('einweisungen.einweisable',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('einweisable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='einweisungen.Einweisable')),
            ],
            bases=('einweisungen.einweisable',),
        ),
        migrations.CreateModel(
            name='Einweisung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('E', 'Instructor'), ('X', 'Allowed'), ('F', 'Advanced')], max_length=1)),
                ('issue_date', models.DateField()),
                ('einweisable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einweisungen.Einweisable')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einweisung_instructor', to='einweisungen.Member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einweisung_member', to='einweisungen.Member')),
            ],
        ),
    ]
