# Generated by Django 3.0.2 on 2020-02-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einweisungen', '0002_auto_20200130_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='einweisable',
            name='etype',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('machine', 'Machine'), ('activity', 'Activity')], default='machine', max_length=200),
        ),
    ]
