# Generated by Django 3.0.2 on 2020-02-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('einweisungen', '0003_einweisable_etype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='einweisung',
            unique_together={('einweisable', 'member', 'level')},
        ),
    ]
