# Generated by Django 4.1.5 on 2023-01-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("einweisungen", "0007_auto_20210717_1556"),
    ]

    operations = [
        migrations.AddField(
            model_name="einweisung",
            name="comment",
            field=models.TextField(null=True),
        ),
    ]
