# Generated by Django 4.1.5 on 2023-01-21 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("einweisungen", "0008_einweisung_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Multieinweisung",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("E", "Instructor"),
                            ("X", "Allowed"),
                            ("F", "Advanced"),
                        ],
                        max_length=1,
                    ),
                ),
                ("issue_date", models.DateField()),
                (
                    "einweisable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="einweisungen.einweisable",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multieinweisung_instructor",
                        to="einweisungen.member",
                    ),
                ),
                ("members", models.ManyToManyField(to="einweisungen.member")),
            ],
            options={
                "verbose_name_plural": "Multi-Einweisungen",
                "permissions": [("view_all", "View all einweisungen")],
            },
        ),
    ]
