# Generated by Django 4.1.6 on 2023-02-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("einweisungen", "0009_multieinweisung"),
    ]

    operations = [
        migrations.AlterField(
            model_name="einweisung",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
